### ISSUE TITLE
Docs links are broken

### ISSUE THREAD

**Issue by aarongarciah** [braposo/figma-graphql#92]
The links in the docs other than the Home one (e.g. https://figma-graphql.party/practical-examples) are broken when accessing them directly giving a 404 error. This must be because routing happens in the client and the server is not configured to serve routes. Seems a problem with GH pages 😢

**Comment by braposo** [comment]
Yes this is a GH pages limitation although there's a hack to get that working: https://github.com/rafrex/spa-github-pages

I think I'll try to deploy the docs to netlify or now for v2 so this is properly fixed instead of trying to make that work with docz.

Thanks for opening the issue anyway! I'll leave this open for reference.

**Comment by braposo** [comment]
This is actually fixed now as part of the upgrade of docz which uses gatsby so it's all statically generated now. Didn't even realise that!
